disabled_rules: # rule identifiers to exclude from running
  - nesting
excluded: # paths to ignore during linting. overridden by `included`.
  - Pods
  - GeneratedFiles
# parameterized rules can be customized from this configuration file
line_length: 140
file_length: 1000
# parameterized rules are first parameterized as a warning level, then error level.
type_body_length:
  - 300 # warning
  - 400 # error
variable_name:
  excluded:
    - id
